[2022-09-04T15:31:45.946+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: example_branch_datetime_operator.datetime_branch manual__2022-09-04T15:31:44.497983+00:00 [queued]>
[2022-09-04T15:31:45.954+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: example_branch_datetime_operator.datetime_branch manual__2022-09-04T15:31:44.497983+00:00 [queued]>
[2022-09-04T15:31:45.954+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-09-04T15:31:45.955+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2022-09-04T15:31:45.957+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-09-04T15:31:45.969+0000] {taskinstance.py:1389} INFO - Executing <Task(BranchDateTimeOperator): datetime_branch> on 2022-09-04 15:31:44.497983+00:00
[2022-09-04T15:31:45.974+0000] {standard_task_runner.py:52} INFO - Started process 526 to run task
[2022-09-04T15:31:45.977+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'example_branch_datetime_operator', 'datetime_branch', 'manual__2022-09-04T15:31:44.497983+00:00', '--job-id', '17', '--raw', '--subdir', '/home/***/.local/lib/python3.7/site-packages/***/example_dags/example_branch_datetime_operator.py', '--cfg-path', '/tmp/tmp9sowa8on', '--error-file', '/tmp/tmpc4kqqyek']
[2022-09-04T15:31:45.978+0000] {standard_task_runner.py:80} INFO - Job 17: Subtask datetime_branch
[2022-09-04T15:31:46.038+0000] {task_command.py:371} INFO - Running <TaskInstance: example_branch_datetime_operator.datetime_branch manual__2022-09-04T15:31:44.497983+00:00 [running]> on host c56acb3a0493
[2022-09-04T15:31:46.102+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=example_branch_datetime_operator
AIRFLOW_CTX_TASK_ID=datetime_branch
AIRFLOW_CTX_EXECUTION_DATE=2022-09-04T15:31:44.497983+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-04T15:31:44.497983+00:00
[2022-09-04T15:31:46.119+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/branch.py", line 52, in execute
    branches_to_execute = self.choose_branch(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/datetime.py", line 85, in choose_branch
    if upper is not None and upper < now:
TypeError: can't compare offset-naive and offset-aware datetimes
[2022-09-04T15:31:46.127+0000] {taskinstance.py:1412} INFO - Marking task as FAILED. dag_id=example_branch_datetime_operator, task_id=datetime_branch, execution_date=20220904T153144, start_date=20220904T153145, end_date=20220904T153146
[2022-09-04T15:31:46.138+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 17 for task datetime_branch (can't compare offset-naive and offset-aware datetimes; 526)
[2022-09-04T15:31:46.150+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-09-04T15:31:46.182+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
